version: '3.1'

services:
  springboot:
    image: darioadesso/git-intel:latest
    restart: always
    container_name: git-intel-springboot
    ports:
      - 8081:8080
    working_dir: /opt/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: git-intel-mongo
    volumes:
      - $HOME/data/git-intel-mongo-data:/data/db
      - $HOME/data/git-intel-mongo-bkp:/data/bkp
    restart: always

  angular:
    image: darioadesso/git-intel-angular:1.0
    container_name: git-intel-angular
    ports:
      - 3000:80
    depends_on:
      - springboot